sudo: true
language: node_js
node_js:
  - "6.3"
  - "4"
  - "8"
  - "10"
  - "12"
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - sudo ln -s /usr/bin/g++-4.8 /usr/local/bin/g++
  - npm install
